apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotellux-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-backend
  template:
    metadata:
      labels:
        app: hotel-backend
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        # Use Netcat (nc) to check the port directly. It's more reliable than DNS
        command: ['sh', '-c', "until nc -zv mysql-db 3306; do echo 'Waiting for MySQL...'; sleep 2; done;"]
      
      containers:
      - name: backend
        image: ravikiranmasule/hotellux-k8s-backend:v15 # Jenkins will update this
        ports:
        - containerPort: 9191
        env:
        - name: DB_HOST
          value: "mysql-db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "Ravikiran@123"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-backend
spec:
  type: NodePort
  selector:
    app: hotel-backend
  ports:
    - port: 9191
      targetPort: 9191
      nodePort: 30001
