apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotellux-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-backend
  template:
    metadata:
      labels:
        app: hotel-backend
    spec:
      containers:
      - name: backend
        image: ravikiranmasule/hotellux-backend:latest # Pulls from DockerHub
        ports:
        - containerPort: 9191
---
apiVersion: v1
kind: Service
metadata:
  name: spring-backend # This matches the name in your Prometheus config
spec:
  selector:
    app: hotel-backend
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191
