apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotellux-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-backend
  template:
    metadata:
      labels:
        app: hotel-backend
    spec:
      containers:
      - name: backend
        image: ravikiranmasule/hotellux-backend:latest
        ports:
        - containerPort: 9191
---
apiVersion: v1
kind: Service
metadata:
  name: spring-backend
spec:
  type: NodePort
  selector:
    app: hotel-backend
  ports:
    - port: 9191
      targetPort: 9191
      nodePort: 30001 # This matches the config.json port
